#! /bin/bash

export GIT_PAIR_SESSION_DIR=$HOME/git-pairing-session
export COAUTHOR_FILE=$GIT_PAIR_SESSION_DIR/.coauthor.json
export PAIRS_FILE=$GIT_PAIR_SESSION_DIR/.pairs.json

alias pairing_project=prepareProjectForPairing
alias pairing_with=setPair
alias no_longer_pairing="rm $COAUTHOR_FILE"
alias paired_with=setCoauthorsForCurrentBranch

setCoauthorsForCurrentBranch() {
  setPair $1 &&
    git filter-branch -f --msg-filter "cat && echo \"\n\nCo-authored-by: $(git config --get user.name) <$(git config --get user.email)>\nCo-authored-by: $(cat $COAUTHOR_FILE | jq -r ".name") <$(cat $COAUTHOR_FILE | jq -r ".email")>\"" master..HEAD &&
    no_longer_pairing
}

prepareProjectForPairing() {
  ln -s -i $GIT_PAIR_SESSION_DIR/hooks/prepare-commit-msg .git/hooks/prepare-commit-msg
}

setPair() {
    echo "{ \"name\": \"$(pairName $1)\", \"email\": \"$(pairEmail $1)\" }" > \
    $COAUTHOR_FILE
}

pairName() {
  cat $PAIRS_FILE | jq -r ".name.$1"
}

pairEmail() {
  cat $PAIRS_FILE | jq -r ".email.$1"
}

