#!/bin/sh
#
# An example hook script to prepare the commit log message.
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.

PAIRINITIALS=$(git config --global --get pair.initials)
if [ $? -eq 0 ]
then
  COMMITER_NAME=$(git config --get user.name)
  COMMITER_EMAIL=$(git config --get user.email)
  COAUTHOR_NAME=$(git config --global --get colleagues.$PAIRINITIALS.name)
  COAUTHOR_EMAIL=$(git config --global --get colleagues.$PAIRINITIALS.email)
  COMMITER="$COMMITER_NAME <$COMMITER_EMAIL>"
  COAUTHOR="$COAUTHOR_NAME <$COAUTHOR_EMAIL>"
  echo "\n\n\nCo-authored-by: $COMMITER\nCo-authored-by: $COAUTHOR" >> "$1"
fi
